In [1]:
import numpy as np

In [3]:
a=np.array([12,23,45,6,45])

In [5]:
print(*a)

12 23 45 6 45


In [7]:
print(a)

[12 23 45  6 45]


In [9]:
a1=np.array((12,23,45,6,45)) #array will be homogenous collection of elements,equal elements in all arrays of dimentions


In [11]:
print(a1)

[12 23 45  6 45]


In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [17]:
#0 dimention array
z=np.array(23)
print(type(z))

<class 'numpy.ndarray'>


In [27]:
#1 dimention array
o=np.array([12,23,45])
print(type(o))
print(o)

<class 'numpy.ndarray'>
[12 23 45]


In [37]:
#2 dimentin array->collection of 1D arrays
t=np.array([[1,2],[5,'4'],[9,8.3]])
print(t)

[['1' '2']
 ['5' '4']
 ['9' '8.3']]


In [51]:
#3 dimention array->one array of two dimentional
t2=np.array([[[12.3,23,4],[4,5,6],[6,8,9]],[[3,4,5],[22,33,44],[55,66,77]]])
print(t2)

[[[12.3 23.   4. ]
  [ 4.   5.   6. ]
  [ 6.   8.   9. ]]

 [[ 3.   4.   5. ]
  [22.  33.  44. ]
  [55.  66.  77. ]]]


In [45]:
#4 dimention array
f=np.array([[[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]]]])
print(f)

[[[[1 2]
   [3 4]]

  [[1 2]
   [3 4]]]


 [[[1 2]
   [3 4]]

  [[1 2]
   [3 4]]]]


In [47]:
#all elements in array will be same
f.dtype

dtype('int32')

In [49]:
t.dtype

dtype('<U32')

In [53]:
t2.dtype

dtype('float64')

In [65]:
#create an array and specify its datatype by yourself-
c=np.array([2,3,4],dtype='S')
print(c)
c.dtype

[b'2' b'3' b'4']


dtype('S1')

In [67]:
d=np.array([2.4,'3',4],dtype='f4')
print(c)
d.dtype

[b'2' b'3' b'4']


dtype('float32')

In [77]:
d=np.array([2.4,True,4])
print(d)
d.dtype

[2.4 1.  4. ]


dtype('float64')

In [5]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #4 one dimentional arrays of same size in two dimentional array

In [7]:
type(a1)

numpy.ndarray

In [9]:
a1.dtype

dtype('int32')

In [13]:
a1.size #so size is number of elements-lowest level/depth pe kitne elements hai

12

In [15]:
a2=np.array([[[],[],[]],[[],[],[]]])

In [17]:
a2.size #0 as there is no elements in array

0

In [21]:
a1.ndim #checking dimentions

2

In [23]:
a2.ndim

3

In [25]:
a3=np.array(2)

In [27]:
a3.ndim

0

In [31]:
#numpy can have any number of dimentions - you can set dimension while creating array
#a1=np.array([1,2,3],ndmin->minimum dimension)

In [33]:
a4=np.array([12,2,3],ndmin=0)#0 minimus it cant be less than 0 but can be greater than 0 so by seeing values it given 1 dimension

In [35]:
a4.ndim

1

In [37]:
a4=np.array([12,2,3],ndmin=2)

In [39]:
a4.ndim

2

In [41]:
a4 #see two extra bracket

array([[12,  2,  3]])

In [43]:
#learn about shape->for knowing the elements in each dimension as size was giving lowest values

In [45]:
a4.shape #1,3 as started from higher to lower,2d me kitne 1d then,1d me kitne elements

(1, 3)

In [47]:
a1.shape

(4, 3)

In [49]:
a2.shape

(2, 3, 0)

In [51]:
a2

array([], shape=(2, 3, 0), dtype=float64)

In [53]:
a3.shape

()

In [55]:
a5=np.array([1,2,3,4,5])
a5.size

5

In [57]:
a5.shape

(5,)

# another way to create numpy array

In [3]:
a1=np.zeros((3,1)) #array me 0s and () me dimensions are given like in a array->3 array->1,1 element which will be 0

In [5]:
a1 #by default data type float

array([[0.],
       [0.],
       [0.]])

In [7]:
a1=np.zeros((3,1),dtype='int')
a1

array([[0],
       [0],
       [0]])

In [13]:
#if u want 1 elemets in array
a2=np.ones((3,2,2),dtype='int')
a2

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [17]:
#if you want all values 2,3or etc ->use function full()
a3=np.full((3,3),22,dtype='int')
print(a3)

[[22 22 22]
 [22 22 22]
 [22 22 22]]


In [19]:
#arange()->ik range me saari values provide karega
a5=np.arange(5)
print(a5)

[0 1 2 3 4]


In [21]:
a2=np.arange(5,10)
print(a2) #arange se one dimension array hi created

[5 6 7 8 9]


In [25]:
#make 2d array with the help of reshape()
#1st make 1d array using arange
a1=np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
#now use reshape function for making it in 2d
a1.reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
a1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a1=a1.reshape(2,5)

In [46]:
a1 #reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
#now if you want elements in gap earlier arange was giving values with gap of one 
a2=np.arange(5,50,5) #extra 5 for giving it gap of 5
print(a2)

[ 5 10 15 20 25 30 35 40 45]


In [52]:
a=np.arange(5,50,3) 
print(a)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [56]:
#reverse it
a=np.arange(60,10,-2) 
print(a)

[60 58 56 54 52 50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14
 12]


In [70]:
#line space

a1=np.linspace(1,10,5,dtype='int')
print(a1) #middle values generated here you are telling total number of elements ki 5 chahiye and gap apne aap se decide hoga in arange u were giving gap

[ 1  3  5  7 10]


In [74]:
a2=np.linspace(1,10,30,dtype='int')
print(a2)

[ 1  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  5  6  6  6  7  7  7  8
  8  8  9  9  9 10]


In [76]:
a1=np.array([[1,2],[3,4],[5,6]])
print(a1)

[[1 2]
 [3 4]
 [5 6]]


In [78]:
a1[1][1]

4

In [80]:
#not a number converting
a1[1][1]=np.nan

ValueError: cannot convert float NaN to integer

In [82]:
#so lets convert the datatype
a1=np.array([[1,2],[3,4],[5,6]],dtype='float')


In [84]:
a1[1][1]=np.nan

In [86]:
print(a1)

[[ 1.  2.]
 [ 3. nan]
 [ 5.  6.]]


In [92]:
#create identity matrix
a1=np.identity(5,dtype='int')

In [94]:
a1 #bz its matrix so dimension will be two

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [104]:
#genearte randome numbers
a1=np.random.rand(2,2,4) #3,4 are shape

In [106]:
a1

array([[[0.81463115, 0.82791578, 0.99446356, 0.62791717],
        [0.89137118, 0.4946008 , 0.87551175, 0.44497502]],

       [[0.87293153, 0.3231247 , 0.97904023, 0.04979235],
        [0.335767  , 0.10759539, 0.95265587, 0.84807383]]])

In [108]:
a1=np.random.randint(8,size=(2,3)) #numbers will be between 1 to 7
a1

array([[7, 3, 4],
       [7, 3, 4]])

In [110]:
a1=np.random.randint(10,15,size=(2,3)) #10 se 14 take
a1

array([[13, 13, 11],
       [10, 11, 11]])

# indexing and slicing

In [4]:
#one d array
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [6]:
for i in a:
    print(i)

10
20
30
40


In [8]:
print(a[1])

20


In [14]:
print(a[3])

40


In [16]:
print(a[-1],a[-2],a[-3],a[-4])

40 30 20 10


In [18]:
#two d
t=np.array([[4,5],[3,6]])
print(t)

[[4 5]
 [3 6]]


In [20]:
t[0]

array([4, 5])

In [22]:
t[1]

array([3, 6])

In [24]:
t[0][0]

4

In [26]:
t[0][1]

5

In [28]:
t[1][0]

3

In [30]:
t[1][1]

6

In [34]:
t[0,1],t[1,1],t[1,0]

(5, 6, 3)

In [36]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [38]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
b.shape

(2, 2, 2)

In [44]:
b[0]

array([[1, 2],
       [3, 4]])

In [46]:
b[1]

array([[5, 6],
       [7, 8]])

In [54]:
b[0,1]

array([3, 4])

In [56]:
b[1,1]

array([7, 8])

In [62]:
b[0,0,0],b[1,1,1],b[0,1,0],b[1,0,1],b[1,1,0]

(1, 8, 3, 6, 7)

In [66]:
b[0,0]

array([1, 2])

In [68]:
b[-1,-1,-1]

8

In [72]:
a=np.array([2,4,6,8,10])
a

array([ 2,  4,  6,  8, 10])

In [74]:
a[1:4:1]

array([4, 6, 8])

In [76]:
a[0:4:1]

array([2, 4, 6, 8])

In [78]:
a[0:4:2]

array([2, 6])

In [82]:
a[-1:-3:-1]

array([10,  8])

In [84]:
a[4:0:-2]

array([10,  6])

In [88]:
a[3::-1] #so you can start from keeping step value negative

array([8, 6, 4, 2])

In [96]:
a[4::-1]

array([10,  8,  6,  4,  2])

In [100]:
a[::-1],a[::1]

(array([10,  8,  6,  4,  2]), array([ 2,  4,  6,  8, 10]))

In [102]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [108]:
a[1::1],a[1::-1]

(array([[4, 5, 6],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [1, 2, 3]]))

In [110]:
a[1:3:1]

array([[4, 5, 6],
       [7, 8, 9]])

In [112]:
a[1:3:1,::-1]

array([[6, 5, 4],
       [9, 8, 7]])

In [114]:
a[0:1:1,0:1:1]

array([[1]])

In [130]:
a[2::,2::],a[0:1:,1:2:]

(array([[9]]), array([[2]]))

In [134]:
a[2::,0:1:]

array([[7]])

In [140]:
a[1,::-1]

array([6, 5, 4])

In [146]:
a[2,0:1:],a[1,2::]

(array([7]), array([6]))

In [148]:
a[0:2,1::1]

array([[2, 3],
       [5, 6]])

# functions

In [151]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# statistics related functions

In [153]:
#arithmetic mean
print(a1.mean())

5.0


In [155]:
#matrix 
#principal diagonal
a1.diagonal()

array([1, 5, 9])

In [157]:
#trace->sum of diagonal
a1.trace()

15

In [159]:
#transpose of matrix->rows and columns interchange or inter replac
a1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
a1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [163]:
#min&max values ->here dimensions dont matter
a1.min()

1

In [165]:
a1.max()

9

In [169]:
#if you want gap/difference between the max value and min value of matrix->ptp(peek-to-peek)
a1.ptp() #max-min

8

In [171]:
#add all values of matrix
a1.sum()

45

In [173]:
#multiplication of matrix values
a1.prod()

362880

In [175]:
#standard deviation
a1.std()

2.581988897471611

In [177]:
#varience
a1.var()

6.666666666666667

# functions for reshaping

In [181]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
a1.size

9

In [187]:
a1.shape #3 1d and in it 3 values

(3, 3)

In [201]:
a1.ndim

2

In [203]:
#you wanna change this shape
a1.reshape([1,9])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [205]:
a1.reshape([9,1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [3]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [5]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
a.reshape([2,4])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a2=a1.flatten() #flatten() a fun by which u can have 1d matrix of any dimension

In [19]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#another method
a3=a1.ravel()
a3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#difference between both
a2[0]=25
a2

array([25,  2,  3,  4,  5,  6,  7,  8,  9])

In [25]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#in above code change in a2 dint affected change in a1


In [31]:
a3[0]=25
a3


array([25,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
a1

array([[25,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
#so here is the difference a3 if used ravel() so it will make change in original matrix as well

In [37]:
#so a2 made the copy of a1,and a3[is a view of a1 as 1d] ravel() changed the view of a1 in 1d its still in 2d array

In [39]:
#copy() and view() functions
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [43]:
b1=a.copy()
b1

array([1, 2, 3, 4])

In [45]:
b1[0]=90

In [47]:
b1

array([90,  2,  3,  4])

In [49]:
a #no change in array

array([1, 2, 3, 4])

In [51]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [53]:
c=b.view()
c

array([1, 2, 3, 4])

In [55]:
c[0]=34
c

array([34,  2,  3,  4])

In [57]:
b #change in original array

array([34,  2,  3,  4])

#check who owns the data="base",if the array has data it will return the original one and if no data owned so none,here copy doesn own the data,view owns the data

In [65]:
a1=np.array([1,2,3,4])
a2=a1.copy()
a3=a1.view()

In [69]:
print(a2.base)

None


In [67]:
print(a3.base)

[1 2 3 4]


In [71]:
print(b1.base)

None


# sort

In [84]:
a=np.array([6,3,2,0,68,39])
a


array([ 6,  3,  2,  0, 68, 39])

In [86]:
a.sort()
a

array([ 0,  2,  3,  6, 39, 68])

In [88]:
c1=np.array([[3,2,4],[5,4,1],[8,6,5]])
c1

array([[3, 2, 4],
       [5, 4, 1],
       [8, 6, 5]])

In [90]:
c1.sort()
c1

array([[2, 3, 4],
       [1, 4, 5],
       [5, 6, 8]])

In [92]:
d1=np.array([[1,2,3],[4,5,6]])
d1

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
#resize function->changing number of elements so you have to tell new shape to it
d1.size

6

In [115]:
d1.resize((3,4),refcheck=False)

In [117]:
d1

array([[1, 2, 3, 4],
       [5, 6, 0, 0],
       [0, 0, 0, 0]])

In [119]:
d1.resize((4,1),refcheck=False)
d1

array([[1],
       [2],
       [3],
       [4]])

 # array manipulation

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1=np.array([[2,2,2],[1,1,1],[1,1,1]])
a+a1

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
a-a1

array([[-1,  0,  1],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [8]:
a*a1 #this tsis not matrix multiplication but multiplication of corrosponding elements

array([[2, 4, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [12]:
#iterate values
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
for i in a:
    for j in i:
        print(j,end=' ')

1 2 3 4 5 6 7 8 9 

In [22]:
#if there are many dimension
for i in np.nditer(a): #this nditer doesnt care about dimensions of array this only direct gives each element of array
    print(i)

1
2
3
4
5
6
7
8
9


In [24]:
f=np.array([[[1,2],[3,4]],[[3,4],[5,6]]])

In [26]:
for i in np.nditer(f):
    print(i,end=' ')

1 2 3 4 3 4 5 6 

In [30]:
#if u want to know elements's index->ndenumarate
for i,e in np.ndenumerate(f):
    print(i,e)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 3
(1, 0, 1) 4
(1, 1, 0) 5
(1, 1, 1) 6


In [32]:
#join arrays
s=np.array([10,20,30])
t=np.array([3,5,15])
d=np.concatenate((s,t))

In [34]:
d

array([10, 20, 30,  3,  5, 15])

In [44]:
e=np.array([[1,2,3],[4,5,6]])
r=np.array([[40,50,60],[9,8,7]])
e1=np.concatenate((e,r))

In [46]:
e1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [40, 50, 60],
       [ 9,  8,  7]])

In [48]:
#specify axis as well
e1=np.concatenate((e,r),axis=0)
e1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [40, 50, 60],
       [ 9,  8,  7]])

In [55]:
e1=np.concatenate((e,r),axis=1)
e1

array([[ 1,  2,  3, 40, 50, 60],
       [ 4,  5,  6,  9,  8,  7]])

In [57]:
a1

array([[2, 2, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a3=np.stack((a,a1),axis=0) #stack generates a new axis every time
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 2, 2],
        [1, 1, 1],
        [1, 1, 1]]])

In [11]:
a1=np.array([10,20,30])
a2=np.array([5,15,25])

In [35]:
a3=np.stack((a1,a2),axis=1)

### 

In [38]:
a3 #stack made it two d

array([[10,  5],
       [20, 15],
       [30, 25]])

In [18]:
a4=np.concatenate((a1,a2))

In [20]:
a4 

array([10, 20, 30,  5, 15, 25])

In [43]:
#array split->in this the numpy arrays stored in a list and each element pair becomes a numpy array
a2=np.array([12,23,34,45,56])
a3=np.array_split(a2,2)

In [46]:
a3

[array([12, 23, 34]), array([45, 56])]

In [52]:
a2=np.array([12,23,34,45,56])
a3=np.array_split(a2,6)

In [54]:
a3

[array([12]),
 array([23]),
 array([34]),
 array([45]),
 array([56]),
 array([], dtype=int32)]

In [60]:
a=np.array([[1,2,3],[10,20,30],[4,5,6],[40,50,60]])
b=np.array_split(a,3)

In [62]:
b

[array([[ 1,  2,  3],
        [10, 20, 30]]),
 array([[4, 5, 6]]),
 array([[40, 50, 60]])]

In [64]:
b=np.array_split(a,4)
b

[array([[1, 2, 3]]),
 array([[10, 20, 30]]),
 array([[4, 5, 6]]),
 array([[40, 50, 60]])]

In [68]:
#search for a elements and u can store its indexes in array as well
a=np.array([1,2,3,4,4,4,6,7,8,4])
x=np.where(a==4)
x

(array([3, 4, 5, 9], dtype=int64),)

In [70]:
#find even numbers
x=np.where(a%2==0)
x

(array([1, 3, 4, 5, 6, 8, 9], dtype=int64),)

In [74]:
#find odd numbers indexes
c=np.where(a%2!=0)
c

(array([0, 2, 7], dtype=int64),)

In [76]:
a1=np.array([[1,5,6],[8,4,3],[7,8,6]])
x=np.where(a1==8)
x #1,0  2,1 pe h

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))

In [78]:
a1

array([[1, 5, 6],
       [8, 4, 3],
       [7, 8, 6]])

In [80]:
a1=np.array([40,30,50])
a2=np.sort(a1)
a2

array([30, 40, 50])

In [90]:
a1=np.array([[50,40],[10,80],[30,70],[60,20]])
a2=np.sort(a1,axis=0)

In [92]:
a2

array([[10, 20],
       [30, 40],
       [50, 70],
       [60, 80]])

In [96]:
a1=np.array([[50,40],[10,80],[30,70],[60,20]])
a2=np.sort(a1,axis=1)
a2

array([[40, 50],
       [10, 80],
       [30, 70],
       [20, 60]])

In [98]:
#see the difference from both with axis 0 it sorted one d array and then all column sort#

In [100]:
#filter out elements in a array
a1=np.array([10,14,26,31,42,53,67])
l=[True,False,True,True,False,False,False]
a1[l] #a1 me se wahi elements filter huee jinke liye corrosponding true tha

array([10, 26, 31])

In [102]:
a1[a1%2] #isme if a1%2 pe if 0 aaya so 0 index ki value printed

array([10, 10, 10, 14, 10, 14, 14])

In [106]:
#seeing greater value than 25
a1[a1>25]

array([26, 31, 42, 53, 67])

# broadcasting

In [4]:
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [6]:
a.shape

(3,)

In [20]:
a1=np.array([1,2,3])
a1.shape

(3,)

In [22]:
a2=np.array([5,6,7,8])
a1+a2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [12]:
#so some time shape is different and broadcasting is not all possible in different shapes

In [26]:
a1

array([1, 2, 3])

In [24]:
a4=np.array([[1],[2],[3]])
a1+a4 #array apne aap ko match ke liye accordingly broadcast kar leta h

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [32]:
a1.shape


(3,)

In [30]:
a4.shape

(3, 1)

In [38]:
b1=np.ones((2,3,5))
b2=np.ones((4,1,5)) #2 or 4 here r not equal nor 1 from both of them

In [40]:
b1+b2

ValueError: operands could not be broadcast together with shapes (2,3,5) (4,1,5) 

In [46]:
b1=np.ones((1,3,5),dtype='int')
b2=np.ones((4,1,5),dtype='int')

In [48]:
b1+b2

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

# structured array

In [5]:
a=np.array([("priya",21,80.0),("raj",22,70.2)])
a[0]

array(['priya', '21', '80.0'], dtype='<U32')

In [53]:
a[1]

array(['raj', '22', '70.2'], dtype='<U32')

In [55]:
a

array([['priya', '21', '80.0'],
       ['raj', '22', '70.2']], dtype='<U32')

In [57]:
a[0][0]

'priya'

In [13]:
a=np.array([("priya",21,80.0),("raj",22,70.2)],dtype=[('name','U10'),('age','int'),('weight','float')]) #data type provided through list of tuples

In [15]:
a

array([('priya', 21, 80. ), ('raj', 22, 70.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [17]:
a[1][0]

'raj'

In [19]:
a[0]

('priya', 21, 80.)

In [21]:
a['name']

array(['priya', 'raj'], dtype='<U10')

In [23]:
a['age'] #understand thus as raw or column

array([21, 22])

In [25]:
#modify
a[0][1]=22

In [27]:
a

array([('priya', 22, 80. ), ('raj', 22, 70.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [29]:
a[0]['age']=23 #change age through raw

In [31]:
a

array([('priya', 23, 80. ), ('raj', 22, 70.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [35]:
a['age'][0]=19 #age changed through column

In [37]:
a

array([('priya', 19, 80. ), ('raj', 22, 70.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [39]:
a['age']=34

In [41]:
a #pure column ki age changed

array([('priya', 34, 80. ), ('raj', 34, 70.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [43]:
#give data type in other ways
#a string of comma seperated
a1=np.array([('priya',21,45.0),('raj',22,78.3)],dtype=('U10,i4,f4'))

In [45]:
a1

array([('priya', 21, 45. ), ('raj', 22, 78.3)],
      dtype=[('f0', '<U10'), ('f1', '<i4'), ('f2', '<f4')])

In [47]:
a1['f0']

array(['priya', 'raj'], dtype='<U10')

In [49]:
a1['f1']

array([21, 22])

In [57]:
#dictionary of field parameters arrays
a1=np.array([('priya',21,45.0),('raj',22,78.3)],dtype={'names':['name','age','weight'],'formats':['U10','i4','f4']})


In [59]:
a1

array([('priya', 21, 45. ), ('raj', 22, 78.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])